### ISSUE TITLE
Status of lights and switches does not update after manual change

### ISSUE THREAD

**Issue by rdagger** [nugget/python-insteonplm#13]
The Insteon devices all work great when controlled from within HA, but when I manually turn a device on or off at the wall switch, the HA status does not update.
Tested with the following:

- Fresh install of the latest version of Hassbian image on RPi2
- Insteon 2413U USB PLM
- Insteon 2477D SwitchLinc Dimmer Switch
- Insteon 2477S SwitchLinc On/Off Switch

I've made no changes to the yaml configuration file other than the following:
```
  customize:
    light.4xxxx4:
      friendly_name: Stairs Light
      icon: mdi:stairs
    light.4xxxxe:
      friendly_name: Entry Light
    light.4xxxx9:
      friendly_name: Hallway Light
      hidden: true
    light.4xxxx1:
      friendly_name: Porch Light
    light.3xxxxe:
      friendly_name: Yard Lights
      icon: mdi:spotlight-beam
    switch.3xxxxa:
      friendly_name: Front Fountain
      icon: mdi:water-pump
    switch.3xxxxc:
      friendly_name: Back Fountain
      icon: mdi:water-pump
    light.3xxxx8:
      friendly_name: Garage Sconces
      icon: mdi:garage

insteon_plm:
  port: /dev/ttyUSB0
  device_override:
    - address: 3xxxxa  # Front fountain
      platform: switch  # Make fountain a switch instead of a light
```
